cub3d 번역초안
42seoul-translation/subject_ko pull request #15
Opened 2020-07-04 13:50 UTC by wrfgt2e

2020-09-28 03:14 UTC, Moongss reviewed
번역 깔끔하게 잘 하신 것 같습니다!
다만 한가지 변경해 주시면 좋겠다는 부분이 있는데요,
275줄에 "무기와 싸울 수 있는 악당"이라 적혀있는데, "무기를 들고 악당과 싸우기"가 적당하지 않을까 생각합니다! 

원문에 "Weapons and bad guys to fight!"라 적혀있어서 그대로 번역하셨는데,
실제로 받아들이는 의미는 무기를 들고 악당과 싸우는 것이 아닐까 싶어서요.

2020-10-10 11:22 UTC, yechoi42 requested changes
전반적으로 잘 읽혔습니다. 수고하쎴어요!!  개인적으로 수정하면 더 좋을 것 같은 부분 덧붙입니다. 판단해서 반영해주세요!! 앞선 피드백도 있어서 approve 대신에 request changes로 요청해요 :)  

2 페이지 `1992년 아포기 소프트웨어에서 발간한, -> 1992년 아포기 소프트웨어에서 출시한,` 게임은 출시라는 표현이 더 어울릴 듯해요.

3 페이지 '정보 연구 -> 정보 검색' 이 더 자연스러워 보여요.

5 페이지 원문에는 must에 강조가 돼있어요. `miniLibX를 사용해야 합니다. -> 반드시 miniLibX를 사용해야 합니다.` 그 바로 다음 문장도 원문에서 괄호가 없으니, 괄호를 빼는 게 좋을 것 같아요. 

`윈도우 관리는 최소화, 다른 창으로 전환 등 완벽해야 합니다. ` 다소 의미가 불분명하게 읽힐 수 있을 것 같아요. smooth의 의미도 '자연스럽다'가 적합할 것 같습니다. `윈도우 관리는 자연스러워야 합니다.(최소화, 다른 창으로 전환 등)` 을 제안해요.  

`벽이 어느 쪽(북, 남, 동, 서)을 향하고 있는지에 따라 다른 벽 질감을 표시해야 합니다.` 이부분도 누락된 괄호를 살려주세요. `벽이 어느 쪽(북, 남, 동, 서)을 향하고 있는지에 따라 다른 벽 질감(질감은 직접 고르세요)을 표시해야 합니다.` 등으로요.

6 페이지 map 위에 생략된 문장이 하나 있어요. `간단하고 유효한 맵의 예시입니다`

2020-12-01 14:06 UTC, yechoi42 approved these changes

2021-03-12 11:00 UTC, hochan222 approved these changes
LGTM :)

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +
```suggestion

# page 1

Contents

| Chapter | Contents | Page |
|:---:|:---|:---:|
| I | [__Foreword__]() | 2 |
| II | [__Goals__]() | 3 |
| III | [__Common Instructions__]() |  4 |
| IV | [__Mandatory part - cub3D__]() |  5 |
| V | [__Bonus part__]() |  9 |
| VI | [__Examples__]() |  11 |

```
목록 추가해보았습니다..!

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  납되지 않을 것입니다.
```suggestion
* 필요한 경우 heap에 할당된 모든 메모리 공간은 적절하게 해제되어야 합니다. 메모리 누수는 용납되지 않을 것입니다.
```
- 띄어쓰기 문제 수정

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  지정하여 컴파일할 것입니다. 그리고 Makefile은 relink 되어서는안됩니다.
```suggestion
  지정하여 컴파일할 것입니다. 그리고 Makefile은 relink 되어서는 안됩니다.
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +* 프로젝트에 보너스를 제출하려면, Makefile에 보너스 규칙을 포함해야 합니다. 이보너스 규칙은
```suggestion
* 프로젝트에 보너스를 제출하려면, Makefile에 보너스 규칙을 포함해야 합니다. 이 보너스 규칙은
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  프로젝트의 메인 부분에서 금지되었던 모든 다양한 헤더, 라이브러리,또는 함수들은 추가해야 할
```suggestion
  프로젝트의 메인 부분에서 금지되었던 모든 다양한 헤더, 라이브러리, 또는 함수들은 추가해야 할
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  트과 보너스 파트는 별도로 평가될 것입니다.
```suggestion
  것입니다. 보너스는 반드시 _bonus.{c/h}라는 다른 파일에 있어야 합니다. 의무적으로 해야 될 파트와 보너스 파트는 별도로 평가될 것입니다.
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  파일한 다음, 프로젝트를 컴파일해야 합니다.
```suggestion
  함께 libft폴더에 복사해야 합니다. 프로젝트의 Makefile은 Makefile을 사용하여 라이브러리를 컴파일한 다음, 프로젝트를 컴파일해야 합니다.
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  니다. 만약 과제를 평가받는데 Deepthought가 배정된다면, 그것은 동료평가 이후에 이루어질 것입니다. 만약 Deepthought 평가 중에 오류가 발생한다면, 그 즉시 평가는 중지될 것입니다.
```suggestion
* 할당된 git 저장소에 과제물을 제출하세요. 오직 git 저장소에 있는 과제물만 등급이 매겨질 것입니다. 만약 과제를 평가받는데 Deepthought가 배정된다면, 그것은 동료평가 이후에 이루어질 것입니다. 만약 Deepthought 평가 중에 오류가 발생한다면, 그 즉시 평가는 중지될 것입니다.
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +  * 지도는 파일 내에서 보이는 것처럼 불러 올수 있어야합니다. 공백은 지도의 유효한 부분이며, 그 처리는 여러분의 몫입니다. 규칙대로 만들어진 어떠한 종류의 지도는 불러올 수 있어야 합니다.
```suggestion
  * 지도는 파일 내에서 보이는 것처럼 불러 올 수 있어야합니다. 공백은 지도의 유효한 부분이며, 그 처리는 여러분의 몫입니다. 규칙대로 만들어진 어떠한 종류의 지도는 불러올 수 있어야 합니다.
```

2021-03-12 11:00 UTC, hochan222 commented on cub3d/cub3d.ko.md
> +평가 중에 다른 기능을 사용하는 것이 정당하다면, 보너스 파트를 완성하기 위해 그러한 기능들을 사용해도 됩니다. 또한 원하는 화면 파일 형식을 필요에 맞게 수정할 수 있습니다. Be smart!
```suggestion
평가 중에 다른 기능을 사용하는 것이 정당하다면, 보너스 파트를 완성하기 위해 그러한 기능들을 사용해도 됩니다. 
또한 원하는 화면 파일 형식을 필요에 맞게 수정할 수 있습니다. 
Be smart!
```

화면에서 잘려서 여러 줄로 개행하는게 좋아보여 리뷰했습니다.

2021-03-12 13:46 UTC, merged