ft_printf 번역초안
42seoul-translation/subject_ko pull request #9
Opened 2020-06-24 08:45 UTC by wrfgt2e

2020-07-06 00:00 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 프로젝트에 보너스를 제출하려면, Makefile에 보너스 규칙을 포함해야 합니다. 이보너스 규칙은
```suggestion
* 보너스 과제를 제출하려면, Makefile에 bonus 규칙을 포함해야 합니다. 이 bonus 규칙으로 
```

2020-07-06 00:00 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +  프로젝트의 메인 부분에서 금지되었던 모든 다양한 헤더, 라이브러리,또는 함수들은 추가해야 할
```suggestion
프로젝트의 메인 파트에서 금지되었던 모든 다양한 헤더, 라이브러리, 또는 함수들을 Makefile에 추가할
```

2020-07-06 00:00 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +  것입니다. 보너스는 반드시 _bonus.{c/h}라는 다른 파일에 있어야 합니다. 의무적으로 해야 될 파
```suggestion
 것입니다. 보너스는 반드시 _bonus.{c/h}라는 다른 파일에 있어야 합니다. 필수 파
```

2020-07-06 00:01 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +  트과 보너스 파트는 별도로 평가될 것입니다.
```suggestion
트과 보너스 파트는 개별적으로 평가될 것입니다.
```

2020-07-06 00:02 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 프로젝트에서 여러분의 libft를 허용한다면, 소스들과 그것과 연관된 Makefile을 연관된 Makefile과
```suggestion
* 프로젝트에서 libft 사용을 허용한다면, libft의 소스 파일과 Makefile을, 관련된 Makefile과
```

2020-07-06 00:02 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +  함께 libft폴더에 복사해야 합니다. 프로젝트의 Makefile은 Makefile을 사용하여 라이브러리를 컴
```suggestion
 함께 libft 폴더에 복사해야 합니다. 여러분들의 Makefile은, 라이브러리 자체 Makefile을 사용하여 라이브러리를 컴
```

2020-07-06 00:04 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 프로젝트에서 여러분의 libft를 허용한다면, 소스들과 그것과 연관된 Makefile을 연관된 Makefile과
이 항목부터 해석이 애매한 것같습니다. 현재진행중인 프로젝트에서 make라고 치면 libft의 make파일을 실행시켜 libft.a를 만들고 그것을 이용하여 현재 프로젝트의 라이브러리를 만들라는 의미로 이해하긴 했는데 이게 맞는지 잘모르겠고, 해석을 어떻게 수정해야할지도 잘모르겠습니다 ..ㅜ

2020-07-06 00:05 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 이 과제물을 제출할 필요가 없고, 채점 받을 필요가 없을지라도, 우리는 프로젝트를 위한 테스트 프로그램을 만들 것을 권장합니다. 그것은 여러분의 과제물과 동료들의 과제물을 쉽게 테스트할 기회를 제공할 것입니다. 평가하는 동안 이 테스트 프로그램들이 특히 유용하다는 것을 알게 될 것입니다. 사실, 평가하는 동안, 여러분의 테스트 프로그램과 평가 받는 동
```suggestion
* 이 과제에서 제출할 필요가 없고, 채점 받을 필요가 없을지라도, 프로젝트를 위한 테스트 프로그램을 작성할 것을 권장합니다. 이 테스트 프로그램은 여러분들의 과제물과 동료들의 과제물을 쉽게 테스트할 기회를 제공할 것입니다. 여러분들은 이 테스트 프로그램들이 평가(defence)를 하는 동안 특히 유용하다는 것을 알게 될 것입니다. 실제로, 평가(defence)하는 동안, 여러분들의 테스트 프로그램과 동료의 테스트 프로그램을 자유롭게 사용할 수 있습니다.
```

2020-07-06 00:05 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 할당된 git 저장소에 과제물을 제출하세요. 오직 git 저장소에 있는 과제물만 등급이매겨질 것입
```suggestion
* 지정된 git 저장소에 과제물을 제출하세요. 오직 git 저장소에 있는 과제물만 채점됩니다.
```

2020-07-06 00:06 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +  니다. 만약 과제를 평가받는데 Deepthought가 배정된다면, 그것은 동료평가 이후에 이루어질 것입니다. 만약 Deepthought 평가 중에 오류가 발생한다면, 그 즉시 평가는 중지될 것입니다.
```suggestion
 Deepthought의 평가는 동료 평가 이후에 수행됩니다. Deepthought의 채점 중 오류가 발생하면, 평가는 즉시 중지됩니다.
```

2020-07-06 00:06 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +Chapter 3
```suggestion
## 제3 장
```

2020-07-06 00:07 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +Mandatory part
```suggestion
### 필수 파트
```

2020-07-06 00:07 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* ft_printf의 프로토타입은 int ft_printf(const char , …); 이여야 합니다.
```suggestion
* ft_printf의 프로토타입은 int ft_printf(const char, ...); 이어야 합니다.
```

2020-07-06 00:09 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +
```suggestion
| 프로그램 명 | libftprintf.a |
| - | - |
| 제출할 파일 | *.c, */*.c, *.h, */*.h, Makefile |
| Makefile | all, clean, fclean, re, bonus |
| 외부 함수 | malloc, free, write, va_start, va_arg, va_copy, va_end |
| Libft 허용 | yes |
| 설명 | 실제 printf의 모방 함수인 ft_printf가 포함된 라이브러리를 작성하십시오 |
```

2020-07-06 00:09 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 당신은 libc의 printf 함수를 다시 코드화해야 합니다.
```suggestion
* libc의 printf 함수를 다시 코딩해야 합니다.
```

2020-07-06 00:09 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 원래의 printf 함수처럼 buffer 관리를 해서는 안 됩니다.
```suggestion
* 실제 printf 함수처럼 버퍼 관리를 수행해서는 안됩니다.
```

2020-07-06 00:10 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 다음과 같은 서식문자들을 관리 할 것입니다: cspdiuxX%
```suggestion
* 다음과 같은 서식 지정자를 구현합니다: cspdiuxX%
```

2020-07-06 00:11 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 모든 서식문자에서 ‘-0.\*’ 플래그와 최소 필드 너비의 조합을 관리 할 것입니다.
```suggestion
* 모든 서식 지정자에서 '-0.\*' 플래그와 최소 필드 너비의 어떤 조합도 처리합니다.
```

2020-07-06 00:12 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 원래의 printf 함수와 비교될 것입니다.
```suggestion
* 실제 printf 함수와 비교될 것입니다.
```

2020-07-06 00:12 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +Chapter 4
```suggestion
## 제4 장
```

2020-07-06 00:12 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +Bonus part
```suggestion
### 보너스 파트
```

2020-07-06 00:13 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 만약 필수적으로 해야하는 부분들이 완벽하지 않다면, 보너스에 대해서는 생각조차 안 할 것입니다.
```suggestion
* 필수 파트가 완벽하지 않은 경우, 보너스에 대해서는 생각하지도 마십시오.
```

2020-07-06 00:13 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 모든 보너스를 수행할 필요는 없습니다.
```suggestion
* 보너스를 모두 구현할 필요는 없습니다.
```

2020-07-06 00:13 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 다음 서식문자 중 하나 이상을 관리하십시오 : nfge
```suggestion
* 다음 서식 지정자 중 하나 이상을 구현하십시오 : nfge
```

2020-07-06 00:15 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 다음 플래그 중 하나 이상을 관리하십시오 : l ll h hh
```suggestion
* 다음 플래그 중 하나 이상을 구현하십시오 : l ll h hh
```

2020-07-06 00:16 UTC, kohyounghwan commented on ft_printf/ft_printf.ko.md
> +* 다음 모든 플래그를 관리하십시오 : ’# +’ (플래그 중 하나는 공백이 맞습니다.)
```suggestion
* 다음 플래그를 모두 구현하십시오 : '# +' (플래그 중 하나는 공백이 맞습니다.)
```

2020-07-16 14:50 UTC, kohyounghwan submitted a review, later dismissed

2020-10-20 15:54 UTC, woolimi requested changes

2020-10-20 15:54 UTC, woolimi commented on ft_printf/ft_printf.ko.md
> +* ft_printf의 프로토타입은 int ft_printf(const char , …); 이어야 합니다.
```suggestion
* ft_printf의 프로토타입은 `int ft_printf(const char *, …);` 이어야 합니다.
```

프로토타입에 char * 별표가 빠졌네요! 그리고 블록으로 표시하면 더 보기 좋을 거 같네요.

2020-10-20 15:54 UTC, woolimi commented on ft_printf/ft_printf.ko.md
> +
• You must use the command ar to create your librairy, using the command libtool
is forbidden.

해당 문장에 대한 번역이 빠졌습니다. 

```suggestion
`ar` 명령어를 이용해 라이브러리를 만들어야 하며, libtool 명령어를 사용하는 것은 금지입니다.
```

2020-10-20 15:54 UTC, woolimi commented on ft_printf/ft_printf.ko.md
> +* 모든 서식문자에서 ‘-0.\*’ 플래그와 최소 필드 너비의 조합을 어떤 조합도 처리할 것입니다.
```suggestion
* 다음과 같은 플래그의 모든 조합을 구현해야 합니다. : ‘-0.\*’ 플래그와 최소 필드 너비가 포함된 모든 서식 지정자.
```
번역을 조금 고쳐보았습니다.

2020-10-20 15:54 UTC, woolimi commented on ft_printf/ft_printf.ko.md
> +| Turn in files    | *.c, */*.c, *.h, */*.h, Makefile                             |
```suggestion
| Turn in files    | \*.c, \*/\*.c, \*.h, \*/\*.h, Makefile                             |
```
마크다운 이스케이프처리를 안해줘서 *이 보이지 않던 오류가 있었습니다.

2021-03-12 08:50 UTC, hochan222 approved these changes
printf 번역 잘 읽었습니다! 고생하셨습니다. 목차 + 몇가지 띄어쓰기 문법 오류 suggestion 작성했습니다.!

2021-03-12 08:50 UTC, hochan222 commented on ft_printf/ft_printf.ko.md
> +
```suggestion

# page 1

Contents

| Chapter | Contents | Page |
|:---:|:---|:---:|
| I | [__Introduction__]() | 2 |
| II | [__Common Instructions__]() | 3 |
| III | [__Mandatory part__]() |  4 |
| IV | [__Bonus part__]() |  5 |

```

2021-03-12 08:50 UTC, hochan222 commented on ft_printf/ft_printf.ko.md
> +  납되지 않습니다.
```suggestion
* 필요한 경우 heap에 할당된 모든 메모리 공간은 적절하게 해제되어야 합니다. 메모리 누수는 용납되지 않습니다.
```

2021-03-12 08:50 UTC, hochan222 commented on ft_printf/ft_printf.ko.md
> +* 프로젝트에 보너스를 제출하려면, Makefile에 `bonus` 규칙을 포함해야하며, 해당 규칙은 프로젝트의 메인 파트에서 금지되었던 모든 다양한 헤더, 라이브러리,또는 함수들을 Makefile에 추가할 수 있습니다. 보너스는 반드시 _bonus.{c/h} 라는 다른 파일에 있어야 합니다. 필수 파트와 보너스 파트는 개별적으로 평가될 것입니다.
```suggestion
* 프로젝트에 보너스를 제출하려면, Makefile에 `bonus` 규칙을 포함해야하며, 해당 규칙은 프로젝트의 메인 파트에서 금지되었던 모든 다양한 헤더, 라이브러리, 또는 함수들을 Makefile에 추가할 수 있습니다. 보너스는 반드시 _bonus.{c/h} 라는 다른 파일에 있어야 합니다. 필수 파트와 보너스 파트는 개별적으로 평가될 것입니다.
```

2021-03-12 13:43 UTC, merged